workspace(name = "tink_cc")

local_repository(
    name = "tink",
    path = "..",
)

load("@tink//:tink_deps.bzl", "tink_deps")
tink_deps()

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")
tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")
tink_cc_deps_init()




